
name: Release

on:
  workflow_call:
    inputs:
      version:
        description: "Release version, must have prerelease branch (e.g 1.2.3 where 1.2.3-alpha exists)"
        required: true
        type: string

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pre-release branch
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.inputs.version }}-alpha"
      
      - name: Create Github Tag and Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.event.inputs.version }}"
          name: "${{ github.event.repository.name }} v${{ github.event.inputs.version }}"
          
      - run: echo ${{ github.event }}
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "${{ github.event.repository.owner.login }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
            
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.event.inputs.version }}"
            
      
