
name: Release

on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prerelease branch
        uses: actions/checkout@v2
        with:
          ref: "${{ github.ref }}"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: "us-west-2"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Parse version from ref name
        id: parse
        run: |
          echo ::set-output name=version::$(echo $GITHUB_REF | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')
          
      - name: Validates that the parsed version is valid semver
        uses: rubenesp87/semver-validation-action@0.0.6
        with:
          version: "${{ steps.parse.outputs.version }}"
        
      - name: Create Github Tag and Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.parse.outputs.version }}"
          name: "${{ github.event.repository.name }} v${{ steps.parse.outputs.version }}"
            
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ steps.parse.outputs.version }}"
            
      
